### ISSUE TITLE
appinio_social_share Share To telegram Error

### ISSUE THREAD

**Issue by k55k32** [appinioGmbH/flutter_packages#119]
exception trace:

```
W/System.err(23450): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND typ=image/png flg=0x10000001 pkg=org.telegram.messenger clip={image/png {T(0) U(content)}} (has extras) }
W/System.err(23450): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2167)
W/System.err(23450): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1807)
W/System.err(23450): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
W/System.err(23450): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
W/System.err(23450): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
W/System.err(23450): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareFileAndTextToPackage(SocialShareUtil.java:297)
W/System.err(23450): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareToTelegram(SocialShareUtil.java:82)
W/System.err(23450): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.decideApp(AppinioSocialSharePlugin.java:103)
W/System.err(23450): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.onMethodCall(AppinioSocialSharePlugin.java:59)
W/System.err(23450): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(23450): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(23450): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(23450): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(23450): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(23450): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(23450): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err(23450): 	at android.os.Looper.loop(Looper.java:299)
W/System.err(23450): 	at android.app.ActivityThread.main(ActivityThread.java:8116)
W/System.err(23450): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23450): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
W/System.err(23450): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by khanmujeeb687** [comment]
Hey @k55k32 , Could you please share your code snippet? And is the telegram app installed on your device?

**Comment by k55k32** [comment]
> Hey @k55k32 , Could you please share your code snippet? And is the telegram app installed on your device?

Code:
```
String file = await bytes.saveToTemporary();
share.shareToTelegram(Locals.share, filePath: file);
```

i install telegram version `9.6.7`. the app package name is : org.telegram.message.web.

may that issue? the package name not match the code

**Comment by khanmujeeb687** [comment]
Hey @k55k32 , The issue is with the package name, the package name is supposed to be `org.telegram.messenger`.
