### ISSUE TITLE
[ BUG ] 🥇  No Activity found to handle 

### ISSUE THREAD

**Issue by WaqasAliAnjum787** [appinioGmbH/flutter_packages#294]
**Appinio social share **

**Describe the bug**
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND flg=0x10000001 pkg=com.whatsapp clip={null {T(0) U(content)}} (has extras) }
Issues while share file on WhatsApp and Twitter  on Android 
//////////////////////////////////////////////////////Logs//////////////////////////////////////////////////////////
W/System.err(27864): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
W/System.err(27864): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1074)
W/System.err(27864): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:411)
W/System.err(27864): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareFileAndTextToPackage(SocialShareUtil.java:385)
W/System.err(27864): 	at com.appinio.socialshare.appinio_social_share.utils.SocialShareUtil.shareToWhatsApp(SocialShareUtil.java:67)
W/System.err(27864): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.decideApp(AppinioSocialSharePlugin.java:111)
W/System.err(27864): 	at com.appinio.socialshare.appinio_social_share.AppinioSocialSharePlugin.onMethodCall(AppinioSocialSharePlugin.java:66)
W/System.err(27864): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err(27864): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/System.err(27864): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)

**Smartphone (please complete the following information):**
 - Device: [e.g. VIVO S1]
 - OS: [e.g. Android 12]

**Comment by khanmujeeb687** [comment]
Hey @WaqasAliAnjum787 , I just tested version `appinio_social_share: ^0.3.1` and its working fine for whatsapp and twitter on Android. Please check this version. Additionally the error you have mentioned only occurs when the targetted app is not installed so please check if you have whatsapp and twitter installed. 

If the issue persists please re open this issue from.

Thanks and have a nice day!

**Comment by WaqasAliAnjum787** [comment]
@khanmujeeb687 
I have WhatsApp and twitter installed on my device, but it does not work.
